### ISSUE TITLE
[BUG] Broken href on windows

### ISSUE THREAD

**Issue by Sharp0802** [Sharp0802/sika#48]
**Problem**

On windows, `SIKA.Test` Failed with message:

```
fail: align-4.html: === EXCEPTION ===
System.Collections.Generic.KeyNotFoundException: The given key 'test0/align-0.md' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SIKA.Components.LinkerBase.OnVisitLink(LinkInline link) in D:\develop\sika\src\SIKA\Components\LinkerBase.cs:line 99
   at MarkdigExtensions.UrlRewriter.UrlRewriterExtension.documentProcessed(MarkdownDocument document)
   at <StartupCode$MarkdigExtensions-UrlRewriter>.$UrlRewriter.-ctor@19.Invoke(MarkdownDocument delegateArg0)
   at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
   at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline, MarkdownParserContext context)
   at SIKA.Components.LinkerBase.<>c__DisplayClass17_1.<Run>b__3(String _) in D:\develop\sika\src\SIKA\Components\LinkerBase.cs:line 152
   at SIKA.Components.SEH.IO[T](T target, Action`1 io) in D:\develop\sika\src\SIKA\Components\SEH.cs:line 28
```

**Expected**

`SIKA.Test` ends with no error.

**Tested Environment**

- Windows 11, version 22H2
- .NET 8.0.100-rc1.23463.5

**Comment by Sharp0802** [comment]
I think It's because on Windows, directory separator is `\` rather than `/`...

**Comment by Sharp0802** [comment]
Tested ACK
